### ISSUE TITLE
[Feature] Improved automation flow

### ISSUE THREAD

**Issue by schaafjs** [cinaq/reminders2calendar#1]
Hi there,

I discovered the original article a couple of days ago and really like the whole approach.

I have one suggestion which in my opinion improves the user experience drastically, especially when mirroring multiple reminder lists. Instead of using a single shortcut per reminder list as done with [`Reminders Personal.shortcut`](https://github.com/cinaq/reminders2calendar/blob/main/Reminders%20Personal.shortcut), you can also use the iterable "for line in text" as a shortcut action to iterate over lines in the user provided text and call [`Reminders2Calendar.shortcut`](https://github.com/cinaq/reminders2calendar/blob/main/Reminders2Calendar.shortcut) for each line (each containing the name of one of the reminder lists). That way only one wrapper shortcut is required for an arbitrary amount of reminder lists.

If you wish, I can also share a minimum working example.

---

On a different note I suggest adding the license of the shortcut also to this repository.

**Comment by xiwenc** [comment]
@schaafjs sounds like a good idea. Please create a PR for the iterable. I was also thinking to make it more flexible so that Reminder List name does not have to match the Calendar name. That's currently a restriction because I could only accept 1 parameter at a time. Could be solved by accepting still 1 parameter but perhaps as a json dictionary. like:

```json
{
"My reminder list1": "calendar 1",
"Another list": "Another calendar"
}
```

**Comment by schaafjs** [comment]
> Please create a PR for the iterable.

Done.

> I was also thinking to make it more flexible so that Reminder List name does not have to match the Calendar name.

I like the idea but am not sure about the implementation. Have you tried something already? When thinking about iterating through a dictionary ([which Shortcuts supports natively](https://support.apple.com/guide/shortcuts/dictionaries-apd43b69f337/ios)), we should also think about error checking in my opinion.

More specifically (in my opinion) the shortcut should ensure:
1. That the provided dictionary/json is of valid form.
2. That the calendar exists.
3. That the reminder exists.

Additionally, the names of the reminder list and calendar should also be extracted to variables and the shortcut actions should only rely on them instead of hardcoded challenges.

**Comment by xiwenc** [comment]
Thanks for PR @schaafjs !
