### ISSUE TITLE
(com.apple.reminderkit error -1.)

### ISSUE THREAD

**Issue by olavesyay** [cinaq/reminders2calendar#2]
im getting this error, what is wrong?
![IMG_0708](https://github.com/cinaq/reminders2calendar/assets/102626282/d54131a9-bb9e-4f94-83ca-cf1356cd3775)

**Comment by xiwenc** [comment]
Did a quick search and found: https://www.reddit.com/r/shortcuts/comments/n7niry/since_the_1451_update_i_have_got_a_problem_with/

Some commented with:

> I got this error too. The way I fixed it was going to the shortcut action that finds reminders and changing the reminder list it filtered for. When the update happened, the list was reset to a list that didn’t support shortcuts (ie a Microsoft account that you’ve linked to the reminders app). After that, the shortcut worked beautifully and fixed some bugs from the previous version. Hope this helps!

is this your case?

**Comment by xiwenc** [comment]
closing this issue until more info is shared. Without reproduction it's hard to fix this.
